### ISSUE TITLE
Existence of unique solutions in AMPL

### ISSUE THREAD

**Issue by TasPinar204** [coin-or/Bonmin#18] opened 2021-01-12 12:02 UTC
Dear Ladies and Gentlemen,

we are using AMPL, the AMPL API for Java and the Solver Bonmin to solve a nonlinear (quadratic) integer based problem. As stated in the theory of the optimization problem there may exist more than one solution. A question is whether it is possible that the solver gives out different solutions, when started with the same initial values several times?

Thank you for the support!
If you have any questions, don't hesitate to ask me.

Best Regards,

Pinar Tas

**Comment by svigerske** [comment] 2021-01-13 02:38
Duplicate of #17

**Closed by svigerske** 2021-01-13 02:38 UTC
